### ISSUE TITLE
Blank files instead of delete files due to OBS's missing files behaviour

### ISSUE THREAD

**Issue by Luna-Nocturna** [Aldaviva/WinampNowPlayingToFile#11]
Hello,

I've since a few days been playing your your plugin and it's the best one I can find for this job. So great job!

However that said if Winamp isn't running when I launch OBS it'll give me the missing files pop up they implemented for missing resource files. Is it possible for the plugin to wipe the content of the txt and save a blank/transparent png if no track is playing and when you exit Winamp?

For the time being I've added "--disable-missing-files-check" at the launch paremeters for OBS but then it'll disable the feature as a whole. Maybe there's also another solution as well I'm unaware of.

Thanks in advance!

**Comment by Aldaviva** [comment]
I have noticed that as well. I usually hit Escape on that dialog box but it is definitely annoying. I'll try the empty file approach you mentioned.

**Comment by Aldaviva** [comment]
Both #5 and #11 should be fixed in the [development snapshot build 24](https://github.com/Aldaviva/WinampNowPlayingToFile/suites/14273276037/artifacts/802115876). You can download that and let me know if they're both working for you. If so, I'll release it as 1.2.0.0.

Note that the default album art is a 1×1 opaque black PNG when the file has no art, when Winamp is paused/stopped, and when you exit Winamp. If you instead want this to be transparent, as written in the issue description, you can save a custom image file to `emptyAlbumArt.png` in the Winamp installation directory.

**Comment by Aldaviva** [comment]
Released in [2.0.0.0](https://github.com/Aldaviva/WinampNowPlayingToFile/releases/tag/2.0.0.0).

There are now two placeholder images you can specify, `emptyAlbumArt.png` when the song has no artwork, and `stoppedAlbumArt.png` when no song is playing. For the OBS case you should probably copy your placeholder image to **both** files.
