### ISSUE TITLE
AIMP support?

### ISSUE THREAD

**Issue by PixelQiwi** [Aldaviva/WinampNowPlayingToFile#2]
Since AIMP pretty much can run Winamp plugins, is there going to be an easily installable AIMP version ("easily installable" as in "using the "install" button inside the Plugins window)?

**Comment by Aldaviva** [comment]
Hi @PixelQiwi, thanks for the suggestion. I will try to look into it. I am not familiar with AIMP, but if it is that compatible with Winamp plugins then it may be easy. The lower-level C++ adapter layer of this plugin comes from [Daniel15/Sharpamp](https://github.com/Daniel15/Sharpamp) so hopefully AIMP can load that.

**Comment by Aldaviva** [comment]
Here are the results of my investigation:
- AIMP plugin ZIP files are unpacked to the `AIMP\Plugins\<pluginName>\` directory, however, [Sharpamp plugins need to have their managed DLLs unpacked to the installation directory](https://github.com/Daniel15/Sharpamp/wiki/Getting-Started#deployment) (`AIMP\`), so the files will be written to the wrong location, preventing the plugin from being loaded.
- If you manually extract each of the DLL files to the correct folder (`gen_WinampNowPlayingToFile.dll` to `AIMP\Plugins\gen_WinampNowPlayingToFile\gen_WinampNowPlayingToFile.dll` and all others to `AIMP\`) then the plugin is loaded and can be enabled from Preferences › Plugins.
- No plugin metadata (author, description) appear in the plugins list, even when I provide a `AIMP\Plugins\gen_WinampNowPlayingToFile\gen_WinampNowPlayingToFile.txt` file.
- The preferences editor UI does load properly when you click the 🔧 button.
- Crucially, no song text or album art is written to the `%TEMP%\winamp_now_playing.<txt|png>` files, probably because the [window message processor from Sharpamp](https://github.com/Daniel15/Sharpamp/blob/master/Sharpamp/Winamp.cs#L208) isn't being initialized or called by AIMP properly. Sharpamp relies on [intercepting `WM_USER` window messages that Winamp sends itself](https://github.com/Daniel15/Sharpamp/blob/master/Sharpamp/Winamp.cs#L237), as far as I can tell.

Since almost none of these behaviors are functional in AIMP, and all of the problems are in other projects where I can't fix them, there is sadly not going to be an easily installable AIMP version of this plugin. Sorry to be the bearer of disappointing news.

If you haven't tried it already, you may want to look at [Current Track Info to Any](http://www.aimp.ru/?do=catalog&rec_id=358).

**Comment by PixelQiwi** [comment]
Well, I have expected that things weren't going to be as easy as just making an archive, however I am pretty certain that Artem, the creator of AIMP, can figure out a way for you and your plugin to function the way you're expecting it to. He even modified AIMP because "Current Track Info to Any" exposed some flaws with the player a couple of times, thus I am not even questioning that you won't regret contacting him about your plugin. 

And if "Current Track Info to Any" wasn't as wooden as it is, I wouldn't have been here in the first place.
