### ISSUE TITLE
Plugin NOT_LOADED | Winamp Stable 5.666

### ISSUE THREAD

**Issue by JDLPIXEL** [Aldaviva/WinampNowPlayingToFile#21]
Hey, das Plugin funktioniert auf meinem Frisch aufgesetztem Laptop nichtmehr.
Winamp lädt bei mir das Plugin auch erst gar nicht, dort steht einfach NICHT GELADEN.
Ich hab schon so viel versucht und ja ich habe auch .NET installiert.
Mehrmals Winamp neu installiert und auch auf einem andern Laptop getestet.
Nichts davon hat geholfen. Vielleicht können Sie mir helfen.

**Comment by Aldaviva** [comment]
Hello, here are some things to check:

1. The installation directory structure requires `gen_WinampNowPlayingToFile.dll` to be in the `Winamp\Plugins` folder, while all of the other DLL files must go in the parent `Winamp` folder (not in the `plugins` subfolder). I believe putting the other DLL files in the `plugins` folder can cause this NOT_LOADED error (`WinampNowPlayingToFile.dll`, `Daniel15.Sharpamp.dll`, `mustache-sharp.dll`, and `taglib-sharp.dll`).
1. Your version of .NET Framework that is installed must be 4.7.2 or later (4.7.2-4.8.1). I like to check this with [ASoft .NET Version Detector](https://www.asoft.be/prod_netver.html).
1. Installing .NET Core (1-3) or .NET (5-9) runtimes won't break this plugin, but they can't run it either, so they are insufficient and .NET Framework is required.

Let me know if any of these ideas are helpful or if the problem is something else.

**Comment by JDLPIXEL** [comment]
Hey, danke für die schnelle Antwort.
Ich habe alle von dir gennannten Einstellungen und Abhängigkeiten überprüft.
Leider funktioniert es nicht, ich habe dir hier mal alle Screenshots angehangen.
![winamp_version](https://github.com/user-attachments/assets/20cb077a-8a75-4208-b424-e59df89b01c6)
![winamp_directory](https://github.com/user-attachments/assets/8417ac93-b1cf-441a-b486-c8f45adca2d6)
![plugin_directory](https://github.com/user-attachments/assets/3a4288b8-b60b-42d0-a694-e0d54950031a)
![NET-Version Detector](https://github.com/user-attachments/assets/1f52be54-6e85-4eb9-9053-63003c4bde3e)
![winamp_plugin_not_loaded](https://github.com/user-attachments/assets/a9a35894-744d-4ad1-8ebc-2ce920f8a14e)

**Comment by Aldaviva** [comment]
Thanks for checking all of those. I'm not sure what's going wrong yet, but I will try to reproduce this issue.

---

Note to self:
- try with Windows' and Winamp's language set to German
- try without any Microsoft Visual C++ Redistributable x86 updates installed, and confirm what the minimum required version is

**Comment by JDLPIXEL** [comment]
Vielen Dank für diese schnelle Hilfestellung.
Es hat tatsächlich funktioniert.
Vielleicht schreiben Sie dies in Ihre Readme

Guten Rutsch ins Neue Jahr :D

**Comment by Aldaviva** [comment]
Fantastic, I'm glad that worked. I always forget about that requirement, but I will definitely add it to the readme now.

Happy New Year to you as well!
