### ISSUE TITLE
Plugin didnt write anything at file except text i write myself in settings

### ISSUE THREAD

**Issue by Anapxist** [Aldaviva/WinampNowPlayingToFile#8]
Hello,
I want to use this plugin for my stream, but i stuck at text part.
I installed the plugin, it make text file at folder i choice but dont write anything in file.
I tryed to change template and it write only thing i write in settings by myself like "-" between artist and song name.
Can you give me any tips where is a problem?
I use winamp 2.95 and windows 7 x64
![1](https://user-images.githubusercontent.com/20355531/191814477-cedffd20-afe7-467c-8b27-ae5d10bc1b4e.PNG)
![2](https://user-images.githubusercontent.com/20355531/191814484-1ff4c7e2-55a3-4b51-96c5-59de3bca73c6.PNG)
![3](https://user-images.githubusercontent.com/20355531/191814487-a8a20e5a-527e-4c9e-b827-2ef92b9dceb5.PNG)

**Comment by Anapxist** [comment]
I use winamp 2.95 and windows 7

**Comment by Aldaviva** [comment]
Hi @Anapxist,

Thanks for reporting this. This plugin is based on the [Sharpamp](https://github.com/Daniel15/Sharpamp) framework, and I'm not sure if that supports Winamp 2. It doesn't declare compatibility with specific Winamp versions. I personally am using it with Winamp 5.666 and haven't tried it with Winamp 2 before.

If you'd like, you can try installing the [official Sharpamp sample Hello World plugin](https://github.com/Aldaviva/WinampNowPlayingToFile/files/9630125/HelloWorldGUI.zip) and see if that detects your song metadata properly. If it works, you should see the following window appear when you restart Winamp, and then it's just a matter of fixing my plugin to make it work like that reference implementation does. If it doesn't work, then Sharpamp is probably not compatible with Winamp 2.

![image](https://user-images.githubusercontent.com/1417794/191872917-e0f873c1-08d1-410d-956c-206d01260d28.png)

*When installing the sample plugin, make sure `HelloWorldGUI.dll` goes in the Winamp installation directory, and `gen_HelloWorldGUI.dll` goes in Winamp's `Plugins` directory.*

*If you get a `NOT LOADED` error, it may caused by a missing Microsoft Visual C++ Redistributable 2008 (x86). I recompiled the sample plugin already, so you don't need the Debug Visual C++ runtime.*

**Comment by Anapxist** [comment]
thank you for your replay. I did what you ask. I got error at winamp start after i install plugin
![4](https://user-images.githubusercontent.com/20355531/191955570-fec2096c-3492-454b-a429-a14b8a0cd6bc.PNG)
Plugin launched, but didn't geather any metadata
![5](https://user-images.githubusercontent.com/20355531/191955703-1ba88c37-140b-4b1f-8f8e-82b7e40105f7.PNG)
Its realy sad coz i like winamp 2.95 and use it for years, now i setup vlc for doing similar thing but i dont like it at all. And you need to start lua every time you start vlc, and it save file at appdata folder etc :(

**Comment by Aldaviva** [comment]
Yeah, I only use VLC for video but I prefer Winamp for audio.

Have you considered trying out Winamp 5? As far as I know it's very similar to 2, including version 2 and 3 skin support and many customization options, as well as a Lite edition which is more like 2.

No pressure if you don't want to migrate, though.

**Comment by Anapxist** [comment]
2.95 dont have library and dont have video support, so it do only what i want from it - playing music :) But i can try other versions i belive it will be batter then VLC anyway. I found some other plugins for old winamp. And i serching for more plugins and find this one:
https://ru.winamp.com/plugin/currently-playing-to-textfile/2326?ysclid=l8fvpe4krf386142719
Its nearly what i need but, sadly it post 2 rows with actor and name and write - winamp not playing when... winamp not playing instead blank :)
Thank you for tips and time anyway.

**Comment by Aldaviva** [comment]
Sounds good. I haven't tried the Lite edition so I don't know if it's exactly what you're looking for or not.

Best of luck with your efforts.
