### ISSUE TITLE
Album Art displaying back box after updating

### ISSUE THREAD

**Issue by DougRedfield87** [Aldaviva/WinampNowPlayingToFile#9]
When I try to update album art for the now playing PNG to load them instead of showing the art it just displays a black box and i update the art in Winamp. how do i fix this so it will show all my album art after i update it?

**Comment by Aldaviva** [comment]
Hello @DougRedfield87,

When the song changes, this plugin uses TagLibSharp to extract the album art to a file. It's possible that there is some incompatibility with file types in TagLibSharp. For example, I seem to recall it not being able to extract album art from Ogg Vorbis files. Feel free to upload an affected audio file somewhere so I can try to reproduce the issue you're experiencing.

**Comment by DougRedfield87** [comment]
how do i do there here? and the files i do use are MP3

**Comment by Aldaviva** [comment]
You should be able to drag and drop the MP3 file into the comment text box on this page and it will upload the file.

**Comment by DougRedfield87** [comment]
[Spider-Man and the X-Men in Arcade's Revenge Music- High Score Table.zip](https://github.com/Aldaviva/WinampNowPlayingToFile/files/10810436/Spider-Man.and.the.X-Men.in.Arcade.s.Revenge.Music-.High.Score.Table.zip)

**Comment by Aldaviva** [comment]
Thanks. Can you upload the album art PNG file as well? It looks like the above MP3 file does not have any album art in it currently.

**Comment by DougRedfield87** [comment]
![Spider-Man   The X-Men in Arcade's Revenge](https://user-images.githubusercontent.com/126127303/220827373-7094a587-a834-4251-bebf-cbdf64aeba43.jpg)

**Comment by Aldaviva** [comment]
I was able to get a similar behavior to reproduce. When I used Winamp to set this MP3 file's album art to the above JPG image with File Info › Artwork › Load Artwork, it copied the JPG file to `Spider-Man & The X-Men in Arcade's Revenge.jpg` in the same folder as the MP3 file, rather than saving it into the MP3 file's ID3 metadata tags.

If you go into File Info › Artwork, can you check what the origin is for your album art?
![image](https://user-images.githubusercontent.com/1417794/220829070-39656a97-a335-401f-9f55-0ca65735913d.png)

If you are able, can you also try embedding the album artwork into the MP3 file to make the origin say `embedded`, so that we can see if this is the problem? You may need to use a program like [TagScanner](https://www.xdlab.ru/en/) or [Mp3tag](https://www.mp3tag.de/en/index.html) to do this.

Since WinampNowPlayingToFile only looks for album art in the media files' metadata, it could not find the artwork, but Winamp also looks for files matching certain names in the same folder as the media file when it is loading artwork. By trying a few common filenames, looking at the strings loaded into Winamp's memory, and monitoring filesystem activity, these seem to include
- the name of the album, which is also how Winamp saves them
- `cover.*`
- `albumart.*`
- `front.*`
- `folder.*`
- `*.nfo` (not sure what contents that is expected to have)

![image](https://user-images.githubusercontent.com/1417794/220830017-6e05f843-1f55-4b91-901c-be1ee22da146.png)

I haven't encountered this before because I almost always embed album art into my media files using TagScanner, because I wanted the artwork to sync to other destinations like my Android phone or YouTube Music, and my artwork usually isn't large enough for the disk savings of a common album art file to be worth it.

It may be possible to make WinampNowPlayingToFile's album art lookup work more like Winamp's, where it also checks for specifically-named files in the same folder as the media file.

**Comment by DougRedfield87** [comment]
so I will try to do that with TagScanner to see if it will embed to it and see if it comes up

**Comment by DougRedfield87** [comment]
so it looks like that was the fix to embed it into the file. Thanks again for the help!

**Comment by Aldaviva** [comment]
Great, glad we figured that out.

There may be a way to make TagScanner or Mp3tag bulk convert album art files into embedded metadata if that's something you want to pursue, I'm not sure.

I can probably also add a new feature to WinampNowPlayingToFile in the future to make its album art finding behave more like Winamp's, where it checks those other files in the same folder as the media file.

**Comment by Aldaviva** [comment]
[The official Winamp forums have an incorrect lookup order](https://forums.winamp.com/forum/winamp/winamp-technical-support/257197-5-5-displaying-wrong-album-art?p=3250096#post3250096) for the album art that Winamp displays. Based on my own verification, the correct list is as follows.

1. embedded
1. `%album%.bmp`
1. `%album%.gif`
1. `%album%.jpeg`
1. `%album%.jpg`
1. `%album%.png`
1. `*.nfo` → treat text contents as image filename
1. `cover.bmp`
1. `cover.gif`
1. `cover.jpeg`
1. `cover.jpg`
1. `cover.png`
1. `folder.bmp`
1. `folder.gif`
1. `folder.jpeg`
1. `folder.jpg`
1. `folder.png`
1. `front.bmp`
1. `front.gif`
1. `front.jpeg`
1. `front.jpg`
1. `front.png`
1. `albumart.bmp`
1. `albumart.gif`
1. `albumart.jpeg`
1. `albumart.jpg`
1. `albumart.png`

**Comment by Aldaviva** [comment]
This development snapshot build should make WinampNowPlayingToFile use the same album art lookup algorithm as Winamp. It will search for external files like `cover.jpg`, and others from the priority list above, in the same directory as the media file.

You can try this out as an alternative to embedding your album art into all your media files.

[WinampNowPlayingToFile.zip build #10](https://github.com/Aldaviva/WinampNowPlayingToFile/files/10812848/WinampNowPlayingToFile.zip)

**Comment by Aldaviva** [comment]
Released this fix in [version 1.1.0.0](https://github.com/Aldaviva/WinampNowPlayingToFile/releases/tag/1.1.0.0).
